//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JA.Risk
{
	internal static partial class Constants
	{
		[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
		public const string DesignerFileExtension = "Risk";
		[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
		public const string ProductName = @"Risk";
		[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
		public const string CompanyName = @"JA";
		[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
		public const string ProductVersion = "1.0.0.0";

		// Menu definitions
		public static readonly global::System.ComponentModel.Design.CommandID RiskDiagramMenu = new global::System.ComponentModel.Design.CommandID(new global::System.Guid(RiskCommandSetId), 0x10000);
		public static readonly global::System.ComponentModel.Design.CommandID RiskExplorerMenu = new global::System.ComponentModel.Design.CommandID(new global::System.Guid(RiskCommandSetId), 0x10001);

		// Command definitions
		public static readonly global::System.ComponentModel.Design.CommandID ViewRiskExplorerCommand = new global::System.ComponentModel.Design.CommandID(new global::System.Guid(RiskCommandSetId), 0x0001);
	
		// Package identifier
		public const string RiskPackageId = "c8c96252-ab8f-4284-84ea-defc13ac854b";
		
		// Editor factory identifier
		public const string RiskEditorFactoryId = "d6887f99-099d-47fe-b69e-c00b0697ca75";
		
		public const string DefaultDiagramExtension = ".diagram";
		
		// Model explorer tool window identifier
		public const string RiskModelExplorerToolWindowId = "621bc91e-8a2f-48e2-a800-b9305ff98891";
	}
}
//
// Constants not generated from values in DesignerDefinition.dsl are defined below
//
namespace JA.Risk
{
	internal static partial class Constants
	{
		// Menu identifier
		public const string RiskCommandSetId = "c3dd4cb7-ffa6-4897-a510-f0461dd951d4";
	}
}