//------------------------------------------------------------------------------
// <auto-generated>
//	 This code was generated by a tool.
//
//	 Changes to this file may cause incorrect behavior and will be lost if
//	 the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using DslModeling = global::Microsoft.VisualStudio.Modeling;
using DslShell = global::Microsoft.VisualStudio.Modeling.Shell;
using DslDiagrams = global::Microsoft.VisualStudio.Modeling.Diagrams;

namespace JA.Risk
{
	/// <summary>
	/// Double-derived class to allow easier code customization.
	/// </summary>
	internal partial class RiskExplorer : RiskExplorerBase
	{
		/// <summary>
		/// Constructs a new RiskExplorer.
		/// </summary>
		public RiskExplorer(global::System.IServiceProvider serviceProvider)
			: base(serviceProvider)
		{
		}
	}
	
	/// <summary>
	/// Control hosted in the RiskExplorerToolWindow.
	/// </summary>
	internal abstract class RiskExplorerBase : DslShell::ModelExplorerTreeContainer
	{
		/// <summary>
		/// Constructs a new RiskExplorerBase.
		/// </summary>
		protected RiskExplorerBase(global::System.IServiceProvider serviceProvider) : base(serviceProvider)
		{
			
			
			// Adds custom tree node settings...
			global::System.Resources.ResourceManager resourceManager = global::JA.Risk.RiskDomainModel.SingletonResourceManager;
			
			this.AddExplorerNodeCustomSetting(global::JA.Risk.Asset.DomainClassId, 
							DslDiagrams::ImageHelper.GetImage(resourceManager.GetObject("AssetExplorerImage")), 
							true); 
			this.AddExplorerNodeCustomSetting(global::JA.Risk.Container.DomainClassId, 
							DslDiagrams::ImageHelper.GetImage(resourceManager.GetObject("ContainerExplorerImage")), 
							true); 
			this.AddExplorerNodeCustomSetting(global::JA.Risk.ThreatAgent.DomainClassId, 
							DslDiagrams::ImageHelper.GetImage(resourceManager.GetObject("ThreatAgentExplorerImage")), 
							true); 
			this.AddExplorerNodeCustomSetting(global::JA.Risk.Port.DomainClassId, 
							DslDiagrams::ImageHelper.GetImage(resourceManager.GetObject("PortExplorerImage")), 
							true); 
			this.AddExplorerNodeCustomSetting(global::JA.Risk.Contains.DomainClassId, 
							DslDiagrams::ImageHelper.GetImage(resourceManager.GetObject("ContainsExplorerImage")), 
							true); 
		}
	
	
	
		/// <summary>
		/// Create IElementVisitor
		/// </summary>
		/// <returns>IElementVisitor</returns>
		protected override DslModeling::IElementVisitor CreateElementVisitor()
		{
			return new DslShell::ExplorerElementVisitor(this);
		}
	
		/// <summary>
		/// Specifies the context menu that should be shown for the model explorer.
		///</summary>
		protected override global::System.ComponentModel.Design.CommandID ContextMenuCommandId
		{
			get
			{
				return Constants.RiskExplorerMenu;
			}
		}
		
		/// <summary>
		/// Returns the root elements domain class Id. The is the very top level tree node in the TreeView
		///</summary>
		protected override global::System.Guid RootElementDomainClassId
		{
			get { return global::JA.Risk.RiskModel.DomainClassId; }
		}
		
		/// <summary>
		/// Returns the root elements to be displayed in the explorer.
		///</summary>
		protected override global::System.Collections.IList FindRootElements(DslModeling::Store store)
		{
			return store.ElementDirectory.FindElements( this.RootElementDomainClassId);
		}
	}
}
	


