//------------------------------------------------------------------------------
// <auto-generated>
//	 This code was generated by a tool.
//
//	 Changes to this file may cause incorrect behavior and will be lost if
//	 the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using DslModeling = global::Microsoft.VisualStudio.Modeling;
using DslShell = global::Microsoft.VisualStudio.Modeling.Shell;
using DslDiagrams = global::Microsoft.VisualStudio.Modeling.Diagrams;

namespace JA.Attack
{
	/// <summary>
	/// Double-derived class to allow easier code customization.
	/// </summary>
	internal partial class AttackExplorer : AttackExplorerBase
	{
		/// <summary>
		/// Constructs a new AttackExplorer.
		/// </summary>
		public AttackExplorer(global::System.IServiceProvider serviceProvider)
			: base(serviceProvider)
		{
		}
	}
	
	/// <summary>
	/// Control hosted in the AttackExplorerToolWindow.
	/// </summary>
	internal abstract class AttackExplorerBase : DslShell::ModelExplorerTreeContainer
	{
		/// <summary>
		/// Constructs a new AttackExplorerBase.
		/// </summary>
		protected AttackExplorerBase(global::System.IServiceProvider serviceProvider) : base(serviceProvider)
		{
			
			
			// Adds custom tree node settings...
			global::System.Resources.ResourceManager resourceManager = global::JA.Attack.AttackDomainModel.SingletonResourceManager;
			
			this.AddExplorerNodeCustomSetting(global::JA.Attack.Task.DomainClassId, 
							DslDiagrams::ImageHelper.GetImage(resourceManager.GetObject("TaskExplorerImage")), 
							true); 
			this.AddExplorerNodeCustomSetting(global::JA.Attack.State.DomainClassId, 
							DslDiagrams::ImageHelper.GetImage(resourceManager.GetObject("StateExplorerImage")), 
							true); 
			this.AddExplorerNodeCustomSetting(global::JA.Attack.Synchronisation.DomainClassId, 
							DslDiagrams::ImageHelper.GetImage(resourceManager.GetObject("SynchronisationExplorerImage")), 
							true); 
			this.AddExplorerNodeCustomSetting(global::JA.Attack.StartPoint.DomainClassId, 
							DslDiagrams::ImageHelper.GetImage(resourceManager.GetObject("StartPointExplorerImage")), 
							true); 
			this.AddExplorerNodeCustomSetting(global::JA.Attack.EndPoint.DomainClassId, 
							DslDiagrams::ImageHelper.GetImage(resourceManager.GetObject("EndPointExplorerImage")), 
							true); 
			this.AddExplorerNodeCustomSetting(global::JA.Attack.MergeBranch.DomainClassId, 
							DslDiagrams::ImageHelper.GetImage(resourceManager.GetObject("MergeBranchExplorerImage")), 
							true); 
			this.AddExplorerNodeCustomSetting(global::JA.Attack.PreCondition.DomainClassId, 
							DslDiagrams::ImageHelper.GetImage(resourceManager.GetObject("PreConditionExplorerImage")), 
							true); 
			this.AddExplorerNodeCustomSetting(global::JA.Attack.PostCondition.DomainClassId, 
							DslDiagrams::ImageHelper.GetImage(resourceManager.GetObject("PostConditionExplorerImage")), 
							true); 
		}
	
	
	
		/// <summary>
		/// Create IElementVisitor
		/// </summary>
		/// <returns>IElementVisitor</returns>
		protected override DslModeling::IElementVisitor CreateElementVisitor()
		{
			return new DslShell::ExplorerElementVisitor(this);
		}
	
		/// <summary>
		/// Specifies the context menu that should be shown for the model explorer.
		///</summary>
		protected override global::System.ComponentModel.Design.CommandID ContextMenuCommandId
		{
			get
			{
				return Constants.AttackExplorerMenu;
			}
		}
		
		/// <summary>
		/// Returns the root elements domain class Id. The is the very top level tree node in the TreeView
		///</summary>
		protected override global::System.Guid RootElementDomainClassId
		{
			get { return global::JA.Attack.AttackGraph.DomainClassId; }
		}
		
		/// <summary>
		/// Returns the root elements to be displayed in the explorer.
		///</summary>
		protected override global::System.Collections.IList FindRootElements(DslModeling::Store store)
		{
			return store.ElementDirectory.FindElements( this.RootElementDomainClassId);
		}
	}
}
	


