//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JA.Attack
{
	internal static partial class Constants
	{
		[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
		public const string DesignerFileExtension = "Attack";
		[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
		public const string ProductName = @"Attack";
		[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
		public const string CompanyName = @"JA";
		[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
		public const string ProductVersion = "1.0.0.0";

		// Menu definitions
		public static readonly global::System.ComponentModel.Design.CommandID AttackDiagramMenu = new global::System.ComponentModel.Design.CommandID(new global::System.Guid(AttackCommandSetId), 0x10000);
		public static readonly global::System.ComponentModel.Design.CommandID AttackExplorerMenu = new global::System.ComponentModel.Design.CommandID(new global::System.Guid(AttackCommandSetId), 0x10001);

		// Command definitions
		public static readonly global::System.ComponentModel.Design.CommandID ViewAttackExplorerCommand = new global::System.ComponentModel.Design.CommandID(new global::System.Guid(AttackCommandSetId), 0x0001);
	
		// Package identifier
		public const string AttackPackageId = "7d9be207-7bdf-414f-925d-c67a372940bf";
		
		// Editor factory identifier
		public const string AttackEditorFactoryId = "4112372e-b85a-4746-987f-7ccf1fbb0485";
		
		public const string DefaultDiagramExtension = ".diagram";
		
		// Model explorer tool window identifier
		public const string AttackModelExplorerToolWindowId = "08d6a4e5-ca5e-44d8-9fb3-5f2bcffce0f1";
	}
}
//
// Constants not generated from values in DesignerDefinition.dsl are defined below
//
namespace JA.Attack
{
	internal static partial class Constants
	{
		// Menu identifier
		public const string AttackCommandSetId = "9b581061-f5bb-4dcb-9894-c0dec4184938";
	}
}